export const space = {
  'spacing-quarck': '0.25rem',
  'spacing-nano': '0.5rem',
  'spacing-xxxxs': '0.75rem',
  'spacing-xxxs': '1rem',
  'spacing-xxs': '1.25rem',
  'spacing-xs': '1.5rem',
  'spacing-sm': '2rem',
  'spacing-md': '2.5rem',
  'spacing-lg': '3rem',
  'spacing-xl': '3.5rem',
  'spacing-xxl': '4rem',
  'spacing-xxxl': '5rem',
  'spacing-xxxxl': '6rem',
  'spacing-huge': '8rem',
  'spacing-gigant': '10rem',
}
